version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: svelte-rpg-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: svelte-rpg
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin